package com.myspace.plannerdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Computer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Cost")
	private int cost;
	@org.kie.api.definition.type.Label("Cpu Power")
	private int cpuPower;
	@org.kie.api.definition.type.Label("Memory")
	private int memory;
	@org.kie.api.definition.type.Label("Network Bandwidth")
	private int networkBandwidth;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;

	public Computer() {
	}

	public int getCost() {
		return this.cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

	public int getCpuPower() {
		return this.cpuPower;
	}

	public void setCpuPower(int cpuPower) {
		this.cpuPower = cpuPower;
	}

	public int getMemory() {
		return this.memory;
	}

	public void setMemory(int memory) {
		this.memory = memory;
	}

	public int getNetworkBandwidth() {
		return this.networkBandwidth;
	}

	public void setNetworkBandwidth(int networkBandwidth) {
		this.networkBandwidth = networkBandwidth;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public Computer(int cost, int cpuPower, int memory, int networkBandwidth,
			java.lang.String name) {
		this.cost = cost;
		this.cpuPower = cpuPower;
		this.memory = memory;
		this.networkBandwidth = networkBandwidth;
		this.name = name;
	}

}