package com.myspace.plannerdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.entity.PlanningEntity
public class Process implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Required Cpu Power")
	private int requiredCpuPower;
	@org.kie.api.definition.type.Label(value = "Required Memory")
	private int requiredMemory;
	@org.kie.api.definition.type.Label(value = "Required Network Bandwidth")
	private int requiredNetworkBandwidth;
	@org.kie.api.definition.type.Label(value = "Computer")
	@org.optaplanner.core.api.domain.variable.PlanningVariable(valueRangeProviderRefs = {"computerRange"})
	private com.myspace.plannerdemo.Computer computer;

	public Process() {
	}

	public int getRequiredCpuPower() {
		return this.requiredCpuPower;
	}

	public void setRequiredCpuPower(int requiredCpuPower) {
		this.requiredCpuPower = requiredCpuPower;
	}

	public int getRequiredMemory() {
		return this.requiredMemory;
	}

	public void setRequiredMemory(int requiredMemory) {
		this.requiredMemory = requiredMemory;
	}

	public int getRequiredNetworkBandwidth() {
		return this.requiredNetworkBandwidth;
	}

	public void setRequiredNetworkBandwidth(int requiredNetworkBandwidth) {
		this.requiredNetworkBandwidth = requiredNetworkBandwidth;
	}

	public com.myspace.plannerdemo.Computer getComputer() {
		return this.computer;
	}

	public void setComputer(com.myspace.plannerdemo.Computer computer) {
		this.computer = computer;
	}

	public Process(int requiredCpuPower, int requiredMemory,
			int requiredNetworkBandwidth,
			com.myspace.plannerdemo.Computer computer) {
		this.requiredCpuPower = requiredCpuPower;
		this.requiredMemory = requiredMemory;
		this.requiredNetworkBandwidth = requiredNetworkBandwidth;
		this.computer = computer;
	}

}