package com.myspace.plannerdemo;

import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.solution.PlanningSolution(autoDiscoverMemberType = org.optaplanner.core.api.domain.autodiscover.AutoDiscoverMemberType.FIELD)
@javax.xml.bind.annotation.XmlRootElement
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
public class Solution implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Computer ist")
	@org.optaplanner.core.api.domain.valuerange.ValueRangeProvider(id = "computerRange")
	private java.util.List<com.myspace.plannerdemo.Computer> computerList;

	@org.kie.api.definition.type.Label("Process List")
	private java.util.List<com.myspace.plannerdemo.Process> processList;

	@org.kie.api.definition.type.Label("Generated Planner score field")
	@javax.annotation.Generated({"org.optaplanner.workbench.screens.domaineditor.client.widgets.planner.PlannerDataObjectEditor"})
	@org.optaplanner.core.api.domain.solution.PlanningScore
	@javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter(org.optaplanner.persistence.jaxb.api.score.buildin.hardsoft.HardSoftScoreJaxbXmlAdapter.class)
	private HardSoftScore score;

	public Solution() {
	}

	public java.util.List<com.myspace.plannerdemo.Computer> getComputerList() {
		return this.computerList;
	}

	public void setComputerList(
			java.util.List<com.myspace.plannerdemo.Computer> computerList) {
		this.computerList = computerList;
	}

	public java.util.List<com.myspace.plannerdemo.Process> getProcessList() {
		return this.processList;
	}

	public void setProcessList(
			java.util.List<com.myspace.plannerdemo.Process> processList) {
		this.processList = processList;
	}

	public org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore getScore() {
		return this.score;
	}

	public void setScore(
			org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore score) {
		this.score = score;
	}

	public Solution(
			java.util.List<com.myspace.plannerdemo.Computer> computerList,
			java.util.List<com.myspace.plannerdemo.Process> processList,
			org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore score) {
		this.computerList = computerList;
		this.processList = processList;
		this.score = score;
	}

}