package com.myspace.plannerdemo;

import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScoreHolder;


global HardSoftScoreHolder scoreHolder;

import com.myspace.plannerdemo.Computer;
import com.myspace.plannerdemo.Process;

// ############################################################################
// Hard constraints
// ############################################################################

rule "Hard CPU power capacity"
    when
        $computer : Computer($cpuPower : cpuPower)
        $requiredCpuPowerTotal : Number(intValue > $cpuPower) from accumulate(
            Process(
                computer == $computer,
                $requiredCpuPower : requiredCpuPower),
            sum($requiredCpuPower)
        )
    then
        scoreHolder.addHardConstraintMatch(kcontext, $cpuPower - $requiredCpuPowerTotal.intValue());
end

rule "Hard memory capacity"
    when
        $computer : Computer($memory : memory)
        $requiredMemoryTotal : Number(intValue > $memory) from accumulate(
            Process(
                computer == $computer,
                $requiredMemory : requiredMemory),
            sum($requiredMemory)
        )
    then
        scoreHolder.addHardConstraintMatch(kcontext, $memory - $requiredMemoryTotal.intValue());
end

rule "Hard network bandwidth capacity"
    when
        $computer : Computer($networkBandwidth : networkBandwidth)
        $requiredNetworkBandwidthTotal : Number(intValue > $networkBandwidth) from accumulate(
            Process(
                computer == $computer,
                $requiredNetworkBandwidth : requiredNetworkBandwidth),
            sum($requiredNetworkBandwidth)
        )
    then
        scoreHolder.addHardConstraintMatch(kcontext, $networkBandwidth - $requiredNetworkBandwidthTotal.intValue());
end

// ############################################################################
// Soft constraints
// ############################################################################

rule "Hosting cost"
    when
        $computer : Computer($cost : cost)
        exists Process(computer == $computer)
    then
        scoreHolder.addSoftConstraintMatch(kcontext, - $cost);
end

